version: '2'
services:
  influxdb:
    image: influxdb:1.8.4
    restart: unless-stopped
    environment:
      INFLUXDB_DB: ats_ngfw
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "9986:8086"

  grafana:
    image: grafana/grafana:7.5.2
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    depends_on:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
