version: '2'
services:
  influxdb:
    image: influxdb:1.8.4
    restart: unless-stopped
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  updater:
    build:
      context: .
      dockerfile: Dockerfile.updater
    restart: unless-stopped
    volumes:
      - ${REPORTS_DIR}:/reports
    depends_on:
      - influxdb
    command:
      - influxdb # FIXME: hostname from previous service
      - ${INFLUXDB_DB}

  grafana:
    image: grafana/grafana:7.5.2
    restart: unless-stopped
    user: "$UID:$GID"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_ROOT_URL: ${GRAFANA_SERVER_ROOT_URL}
    depends_on:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
