{
 "title": "NGFW ATS",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "public_version",
    "label": "Full version",
    "query": "SHOW TAG VALUES WITH key = \"public_version\""
   },
   { "name": "distribution", "label": "Distribution", "query": "current" }
  ]
 },
 "panels": [
  {
   "title": "Run duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Duration in minutes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "launch_time",
     "select": [
      [
       { "params": [ "sum_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    }
   ]
  },
  {
   "title": "# skipped tests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "# skipped tests",
     "measurement": "launch_status",
     "query": "SELECT mean(\"skipped\") FROM \"launch_status\" WHERE (\"public_version\" =~ /^$public_version$/) AND (\"distributions\" =~ /$distribution;/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Without skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "launch_status",
     "query": "SELECT mean(\"ratio\") FROM (SELECT 100*\"passed\"/(\"failed\"+\"passed\") as \"ratio\" FROM \"launch_status\" WHERE (\"public_version\" =~ /^$public_version$/) AND (\"distributions\" =~ /$distribution;/)) WHERE $timeFilter  GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" }
     ]
    },
    {
     "alias": "With skipped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "launch_status",
     "query": "SELECT mean(\"ratio\") FROM (SELECT 100*\"passed\"/(\"failed\"+\"passed\"+\"skipped\") as \"ratio\" FROM \"launch_status\"  WHERE (\"public_version\" =~ /^$public_version$/) AND (\"distributions\" =~ /$distribution;/)) WHERE $timeFilter  GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    }
   ]
  },
  {
   "title": "Test results",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "passed",
     "measurement": "launch_status",
     "select": [
      [
       { "params": [ "passed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    },
    {
     "alias": "skipped",
     "measurement": "launch_status",
     "select": [
      [
       { "params": [ "skipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    },
    {
     "alias": "failed",
     "measurement": "launch_status",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    },
    {
     "alias": "broken",
     "measurement": "launch_status",
     "query": "SELECT mean(\"broken\") FROM \"launch_status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "broken" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "public_version", "operator": "=~", "value": "/^$public_version$/" },
      { "condition": "AND", "key": "distributions", "operator": "=~", "value": "/$distribution;/" }
     ]
    }
   ]
  }
 ]
}